In [52]:
from enum import IntEnum

class _dataframe_field(IntEnum):
    original_index = 0
    line_flag = 1
    circle_flag = 2
    arc_flag = 3
    point_flag = 4
    start_x = 5
    start_y = 6
    end_x = 7
    end_y = 8
    mid_x = 9
    mid_y = 10
    angle = 11
    length = perimeter = 12
    d_x = 13
    d_y = 14
    u_x = 15
    u_y = 16
    n_x = 17
    n_y = 18
    center_x = 19
    center_y = 20
    radius = 21
    start_angle = 22
    end_angle = 23
    arc_span = 24
    
    @classmethod
    def count(cls) -> int: return len(cls)

class _edge_attribute(IntEnum):
    parallel = 0
    colinear = 1
    perpendicular_distance = 2
    overlap_ratio = 3
    oblique = 4
    intersection_position = 5
    angle_difference_sin = 6
    angle_difference_cos = 7
    
    @classmethod
    def count(cls) -> int: return len(cls)

from typing import Tuple
import torch
from torch import Tensor
from torch import newaxis

def create_obbs(elements:Tensor, width:float, length_extension:float=0.0) -> Tuple[Tensor, Tensor]:
    
    F = _dataframe_field
    n_elements = elements.size(1)
    
    # Filter supported elements
    is_line = elements[F.line_flag] == 1
    is_circle_or_arc = (elements[F.circle_flag] == 1) | (elements[F.arc_flag] == 1)
    
    filter = is_line | is_circle_or_arc
    
    obbs = torch.empty((n_elements, 4, 2), dtype=torch.float32)
    
    if is_line.any():
        # === LINE ELEMENTS ===
        lines = elements[:, is_line]
        
        # Half dimensions
        half_width = width / 2
        half_length = (lines[F.length] + length_extension) / 2
        
        # Compute displacements
        dx_length = lines[F.u_x] * half_length
        dy_length = lines[F.u_y] * half_length
        dx_width = lines[F.n_x] * half_width
        dy_width = lines[F.n_y] * half_width
        
        # Corners (4 per OBB)
        corner1 = torch.stack([lines[F.mid_x] - dx_length - dx_width,
                                lines[F.mid_y] - dy_length - dy_width], dim=1)
        
        corner2 = torch.stack([lines[F.mid_x] + dx_length - dx_width,
                                lines[F.mid_y] + dy_length - dy_width], dim=1)
        
        corner3 = torch.stack([lines[F.mid_x] + dx_length + dx_width,
                                lines[F.mid_y] + dy_length + dy_width], dim=1)
        
        corner4 = torch.stack([lines[F.mid_x] - dx_length + dx_width,
                                lines[F.mid_y] - dy_length + dy_width], dim=1)
        
        # Stack corners
        obbs[is_line] = torch.stack([corner1, corner2, corner3, corner4], dim=1)
    
    if is_circle_or_arc.any():
        # === ARC ELEMENTS ===
        arcs = elements[:, is_circle_or_arc]
        
        margin = width / 2
        
        u_x, u_y, n_x, n_y = arcs[F.u_x], arcs[F.u_y], arcs[F.n_x], arcs[F.n_y]
        arc_span, radius = arcs[F.arc_span], arcs[F.radius]
        
        dx_length = torch.where(arc_span < torch.pi, n_x * (radius * torch.sin(arc_span/2) + margin), n_x * (radius + margin))
        dy_length = torch.where(arc_span < torch.pi, n_y * (radius * torch.sin(arc_span/2) + margin), n_y * (radius + margin))
        
        dx_width = u_x * (radius * (1 - torch.cos(arc_span/2)) + margin)
        dy_width = u_y * (radius * (1 - torch.cos(arc_span/2)) + margin)
        
        dx_margin = u_x * margin
        dy_margin = u_y * margin
        
        corner1 = torch.stack([arcs[F.mid_x] - dx_length + dx_margin,
                                arcs[F.mid_y] - dy_length + dy_margin], dim=1)
        
        corner2 = torch.stack([arcs[F.mid_x] + dx_length + dx_margin,
                                arcs[F.mid_y] + dy_length + dy_margin], dim=1)
        
        corner3 = torch.stack([arcs[F.mid_x] + dx_length - dx_width,
                                arcs[F.mid_y] + dy_length - dy_width], dim=1)
        
        corner4 = torch.stack([arcs[F.mid_x] - dx_length - dx_width,
                                arcs[F.mid_y] - dy_length - dy_width], dim=1)
        
        obbs[is_circle_or_arc] = torch.stack([corner1, corner2, corner3, corner4], dim=1)
    
    elements = elements[:, filter]
    obbs = obbs[filter]
    
    return elements, obbs # Shape obbs (n_elements, 4, 2)

def get_overlaping_pairs(elements:Tensor, obbs:Tensor) -> Tuple[Tensor, Tensor]:
    
    F = _dataframe_field
    
    # Compute AABBs (Axis-Aligned Bounding Boxes)
    min_x = obbs[..., 0].min(dim=1).values
    max_x = obbs[..., 0].max(dim=1).values
    min_y = obbs[..., 1].min(dim=1).values
    max_y = obbs[..., 1].max(dim=1).values
    
    # Computing AABB intersection matrix
    mask_x = (min_x[:, newaxis] <= max_x[newaxis, :]) & (min_x[newaxis, :] <= max_x[:, newaxis])
    mask_y = (min_y[:, newaxis] <= max_y[newaxis, :]) & (min_y[newaxis, :] <= max_y[:, newaxis])
    aabb_overlap = mask_x & mask_y
    
    # Candidate pairs
    pairs = torch.argwhere(aabb_overlap) # shape (n, 2)
    i, j = pairs[:, 0], pairs[:, 1]
    
    # Remove self-comparisons and duplicates
    mask = (i < j)
    i, j = i[mask], j[mask]
    
    # Get OBBs for pairs
    obbs_i, obbs_j = obbs[i], obbs[j]
    
    # axes per box
    axes_i = torch.stack([elements[F.u_x, i], elements[F.u_y, i], elements[F.n_x, i], elements[F.n_y, i]], dim=1).reshape(-1,2,2)
    axes_j = torch.stack([elements[F.u_x, j], elements[F.u_y, j], elements[F.n_x, j], elements[F.n_y, j]], dim=1).reshape(-1,2,2)
    axes = torch.cat([axes_i, axes_j], axis=1) # shape (n_pairs, 4, 2)
    
    # Project corners onto axes
    projections_i = torch.einsum('nij,nkj->nik', axes, obbs_i) # Shape (n_pairs, 4, 4)
    projections_j = torch.einsum('nij,nkj->nik', axes, obbs_j)
    
    # Interval comparisons on each axis
    min_i = projections_i.min(dim=2).values
    max_i = projections_i.max(dim=2).values
    min_j = projections_j.min(dim=2).values
    max_j = projections_j.max(dim=2).values
    
    separating_axis = (max_i < min_j) | (max_j < min_i) # True if a separating axis exists
    obb_overlap = ~torch.any(separating_axis, dim=1) # True if overlap
    
    return i[obb_overlap], j[obb_overlap]


In [53]:
F = _dataframe_field
dataframe = torch.zeros((F.count(), 30), dtype=torch.float32)
dataframe[F.original_index] = torch.tensor([   0,  1,   2,   3,   5,   4,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19,   20,   21,   22,   23,   24,   25,   26,   27,   28,   29])
dataframe[F.line_flag] =      torch.tensor([   0,  1,   0,   1,   1,   0,   0,   1,   0,   1,   0,   1,   0,   1,   0,   1,   0,   1,   0,   1,    0,    1,    0,    1,    0,    1,    0,    1,    0,    1])
dataframe[F.circle_flag] =    torch.tensor([   1,  0,   1,   0,   0,   1,   1,   0,   1,   0,   1,   0,   1,   0,   1,   0,   1,   0,   1,   0,    1,    0,    1,    0,    1,    0,    1,    0,    1,    0])
dataframe[F.start_x] =        torch.tensor([   0, 40,   0, 100, 200,   0,   0, 390,   0, 402,   0, 550,   0, 610,   0, 710,   0, 880,   0, 910,    0, 1078,    0, 1104,    0, 1295,    0, 1325,    0, 1450])
dataframe[F.start_y] =        torch.tensor([   0, 10,   0,  41,  30,   0,   0,  30,   0,  30,   0,  30,   0, -30,   0, -20,   0,  35,   0, -35,    0,   30,    0,  -30,    0,   30,    0,   30,    0,  -39])
dataframe[F.end_x] =          torch.tensor([   0, 60,   0, 145, 240,   0,   0, 300,   0, 422,   0, 590,   0, 670,   0, 800,   0, 900,   0, 960,    0, 1098,    0, 1124,    0, 1275,    0, 1390,    0, 1450])
dataframe[F.end_y] =          torch.tensor([   0, 10,   0,  41,  30,   0,   0,  30,   0,  30,   0,  30,   0,  50,   0, -20,   0,  35,   0, -15,    0,   30,    0,  -30,    0,   30,    0,   30,    0,   39])
dataframe[F.center_x] =       torch.tensor([  50,  0, 150,   0,   0, 250, 350,   0, 450,   0, 550,   0, 650,   0, 750,   0, 850,   0, 950,   0, 1050,    0, 1150,    0, 1250,    0, 1350,    0, 1450,    0])
dataframe[F.center_y] =       torch.tensor([   0,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0])
dataframe[F.radius] =         torch.tensor([  40,  0,  40,   0,   0,  40,  40,   0,  40,   0,  40,   0,  40,   0,  40,   0,  40,   0,  40,   0,   40,    0,   40,    0,   40,    0,   40,    0,   40,    0])
dataframe[F.start_angle] =    torch.tensor([   0,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0])
dataframe[F.end_angle] =      torch.tensor([ 360,  0, 360,   0,   0, 360, 360,   0, 360,   0, 360,   0, 360,   0, 360,   0, 360,   0, 360,   0,  360,    0,  360,    0,  360,    0,  360,    0,  360,    0])

In [54]:
# === LINES ===
is_line = dataframe[F.line_flag] == 1

min_length = 1e-3

dataframe[F.mid_x] = torch.where(is_line, (dataframe[F.start_x] + dataframe[F.end_x]) / 2, dataframe[F.mid_x])
dataframe[F.mid_y] = torch.where(is_line, (dataframe[F.start_y] + dataframe[F.end_y]) / 2, dataframe[F.mid_y])

dataframe[F.d_x] = torch.where(is_line, dataframe[F.end_x] - dataframe[F.start_x], dataframe[F.d_x])
dataframe[F.d_y] = torch.where(is_line, dataframe[F.end_y] - dataframe[F.start_y], dataframe[F.d_y])
dataframe[F.angle] = torch.where(is_line, torch.arctan2(dataframe[F.d_y], dataframe[F.d_x]) % torch.pi, dataframe[F.angle])
dataframe[F.length] = torch.where(is_line, torch.sqrt(dataframe[F.d_x]**2 + dataframe[F.d_y]**2), dataframe[F.length])

is_line &= (dataframe[F.length] > min_length)

# Unit direction and unit perpendicular vectors
dataframe[F.u_x] = torch.where(is_line, dataframe[F.d_x] / dataframe[F.length], dataframe[F.u_x])
dataframe[F.u_y] = torch.where(is_line, dataframe[F.d_y] / dataframe[F.length], dataframe[F.u_y])
dataframe[F.n_x] = torch.where(is_line, -dataframe[F.u_y], dataframe[F.n_x])
dataframe[F.n_y] = torch.where(is_line, dataframe[F.u_x], dataframe[F.n_y])

# === POINTS ===
is_point = dataframe[F.point_flag] == 1

for field in [F.start_x, F.end_x]: dataframe[field] = torch.where(is_point, dataframe[F.mid_x], dataframe[field])
for field in [F.start_y, F.end_y]: dataframe[field] = torch.where(is_point, dataframe[F.mid_y], dataframe[field])

is_line_point = (dataframe[F.line_flag] == 1) & (dataframe[F.length] <= min_length)

dataframe[F.point_flag] = torch.where(is_line_point, 1, dataframe[F.point_flag])
dataframe[F.line_flag] = torch.where(is_line_point, 0, dataframe[F.line_flag])

# === CIRCLES AND ARCS ===
is_circle = dataframe[F.circle_flag] == 1
is_arc = dataframe[F.arc_flag] == 1
is_circle_or_arc = is_circle | is_arc

dataframe[F.start_angle] = torch.where(is_circle_or_arc, torch.deg2rad(dataframe[F.start_angle]), dataframe[F.start_angle])
dataframe[F.end_angle] = torch.where(is_circle_or_arc, torch.deg2rad(dataframe[F.end_angle]), dataframe[F.end_angle])

dataframe[F.arc_span] = torch.where(is_circle, 2 * torch.pi, dataframe[F.arc_span])
dataframe[F.arc_span] = torch.where(is_arc, ((dataframe[F.end_angle] - dataframe[F.start_angle]) % (2*torch.pi)), dataframe[F.arc_span])

mid_angle = torch.where(is_circle_or_arc, (dataframe[F.start_angle] + dataframe[F.arc_span] / 2) % (2*torch.pi), 0)

dataframe[F.start_x] = torch.where(is_circle_or_arc, dataframe[F.center_x] + dataframe[F.radius] * torch.cos(dataframe[F.start_angle]), dataframe[F.start_x])
dataframe[F.start_y] = torch.where(is_circle_or_arc, dataframe[F.center_y] + dataframe[F.radius] * torch.sin(dataframe[F.start_angle]), dataframe[F.start_y])
dataframe[F.end_x] = torch.where(is_circle_or_arc, dataframe[F.center_x] + dataframe[F.radius] * torch.cos(dataframe[F.end_angle]), dataframe[F.end_x])
dataframe[F.end_y] = torch.where(is_circle_or_arc, dataframe[F.center_y] + dataframe[F.radius] * torch.sin(dataframe[F.end_angle]), dataframe[F.end_y])
dataframe[F.mid_x] = torch.where(is_circle_or_arc, dataframe[F.center_x] + dataframe[F.radius] * torch.cos(mid_angle), dataframe[F.mid_x])
dataframe[F.mid_y] = torch.where(is_circle_or_arc, dataframe[F.center_y] + dataframe[F.radius] * torch.sin(mid_angle), dataframe[F.mid_y])

dataframe[F.u_x] = torch.where(is_circle_or_arc, (dataframe[F.mid_x] - dataframe[F.center_x]) / dataframe[F.radius], dataframe[F.u_x])
dataframe[F.u_y] = torch.where(is_circle_or_arc, (dataframe[F.mid_y] - dataframe[F.center_y]) / dataframe[F.radius], dataframe[F.u_y])
dataframe[F.n_x] = torch.where(is_circle_or_arc, -dataframe[F.u_y], dataframe[F.n_x])
dataframe[F.n_y] = torch.where(is_circle_or_arc, dataframe[F.u_x], dataframe[F.n_y])

dataframe[F.perimeter] = torch.where(is_circle_or_arc, dataframe[F.radius] * dataframe[F.arc_span], dataframe[F.perimeter])

In [56]:
line_obb_width=2
parallel_angle_tolerance=0.02

obb_width=None; angle_tolerance=None

obb_width = obb_width or line_obb_width
angle_tolerance = (angle_tolerance or parallel_angle_tolerance) * torch.pi/180

In [57]:
# Compute OBBs
elements, obbs = create_obbs(elements=dataframe, width=obb_width, length_extension=obb_width) # Shape obbs (n_lines, 4, 2)

In [58]:
# Get the pairs of overlapping obbs
i, j = get_overlaping_pairs(elements, obbs)
elements_a, elements_b = elements[:, i], elements[:, j]

In [59]:
# Compute absolute angle difference for line-line pairs in [0, pi]
line_line_pair = (elements_a[F.line_flag] == 1) & (elements_b[F.line_flag] == 1)
angle_difference = torch.where(line_line_pair, torch.abs(elements_a[F.angle] - elements_b[F.angle]), 0)
angle_difference = torch.where(line_line_pair, torch.minimum(angle_difference, torch.pi - angle_difference), angle_difference)

# Keep only pairs with angle difference above threshold
oblique = torch.where(line_line_pair, angle_difference > angle_tolerance, True)
elements_a, elements_b = elements_a[:, oblique], elements_b[:, oblique]

In [61]:
n_elements = elements_a.size(1)

# Filter supported pairs
is_line_a = elements_a[F.line_flag] == 1
is_line_b = elements_b[F.line_flag] == 1
is_arc_a = (elements_a[F.circle_flag] == 1) | (elements_a[F.arc_flag] == 1)
is_arc_b = (elements_b[F.circle_flag] == 1) | (elements_b[F.arc_flag] == 1)

line_line_pair = is_line_a & is_line_b
line_arc_pair, arc_line_pair = is_line_a & is_arc_b, is_arc_a & is_line_b

filter = line_line_pair | (line_arc_pair | arc_line_pair)

In [62]:
intersection_a_min = torch.empty(n_elements, dtype=torch.float32)
intersection_a_max = torch.empty(n_elements, dtype=torch.float32)
intersection_b_min = torch.empty(n_elements, dtype=torch.float32)
intersection_b_max = torch.empty(n_elements, dtype=torch.float32)

In [63]:
lines_a, arcs_b = elements_a[:, line_arc_pair], elements_b[:, line_arc_pair]
arcs_a, lines_b = elements_a[:, arc_line_pair], elements_b[:, arc_line_pair]

In [64]:
arcs = arcs_a
lines = lines_b

In [23]:
dx_start = arcs[F.center_x] - lines[F.start_x]
dy_start = arcs[F.center_y] - lines[F.start_y]
dx_end = arcs[F.center_x] - lines[F.end_x]
dy_end = arcs[F.center_y] - lines[F.end_y]

In [24]:
distance_start = torch.sqrt(dx_start**2 + dy_start**2)
distance_end = torch.sqrt(dx_end**2 + dy_end**2)
distance_start, distance_end

(tensor([]), tensor([]))

In [ ]:
inner_radius = arcs[F.radius] - obb_width

In [51]:
# Remove pairs in which the lines falls completelly within the circle inner perimeter
start_in_inner = distance_start < inner_radius
end_in_inner = distance_end < inner_radius
start_in_inner, end_in_inner

(tensor([ True, False, False, False,  True, False, False, False, False, False,
         False, False, False, False]),
 tensor([ True, False, False, False, False, False, False, False,  True, False,
         False, False, False, False]))

In [52]:
mask = ~(start_in_inner & end_in_inner)
mask

tensor([False,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True])

In [ ]:
arcs, lines = arcs[:, mask], lines[:, mask]
dx_start, dy_start = dx_start[mask], dy_start[mask]
inner_radius = inner_radius[mask]
start_in_inner, end_in_inner = start_in_inner[mask], end_in_inner[mask]

In [54]:
# Compute closest distance betweem the center of the circle and the line
t = torch.clamp((dx_start * lines[F.d_x] + dy_start * lines[F.d_y]) / lines[F.length]**2, min=0, max=1)
t

tensor([1.0000, 0.4444, 1.0000, 0.0000, 0.4800, 0.4444, 0.0000, 0.9310, 0.0000,
        1.0000, 1.0000, 0.3846, 0.5000])

In [55]:
closest_x, closest_y = lines[F.start_x] + t * lines[F.d_x], lines[F.start_y] + t * lines[F.d_y]
closest_x, closest_y

(tensor([ 145.0000,  350.0000,  422.0000,  550.0000,  638.8000,  750.0000,
          880.0000,  956.5518, 1078.0000, 1124.0000, 1275.0000, 1350.0000,
         1450.0000]),
 tensor([ 41.0000,  30.0000,  30.0000,  30.0000,   8.4000, -20.0000,  35.0000,
         -16.3793,  30.0000, -30.0000,  30.0000,  30.0000,   0.0000]))

In [ ]:
closest_distance = torch.sqrt((closest_x - arcs[F.center_x])**2 + (closest_y - arcs[F.center_y])**2)
closest_distance

tensor([41.3038, 30.0000, 41.0366, 30.0000, 14.0000, 20.0000, 46.0977, 17.6411,
        41.0366, 39.6989, 39.0512, 30.0000,  0.0000])

In [ ]:
outer_radius = arcs[F.radius] + obb_width

In [58]:
# Remove pairs in which the lines falls completelly out of the circle outer perimeter
mask = ~(closest_distance > outer_radius)
mask

tensor([ True,  True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True])

In [ ]:
arcs, lines = arcs[:, mask], lines[:, mask]
dx_start, dy_start = dx_start[mask], dy_start[mask]
inner_radius = inner_radius[mask]
start_in_inner, end_in_inner = start_in_inner[mask], end_in_inner[mask]
closest_distance = closest_distance[mask]

In [ ]:
a = lines[F.u_x]**2 + lines[F.u_y]**2
b = 2 * (dx_start * lines[F.u_x] + dy_start * lines[F.u_y])
c = dx_start**2 + dy_start**2 - arcs[F.radius]**2
discriminant = torch.clamp(b**2 - 4 * a * c, min=0)
discriminant

tensor([   0.0000, 2800.0000, 2800.0000, 2800.0000, 5616.0000, 4800.0000,
        5155.1719, 2800.0000, 2800.0000, 2800.0000, 2800.0000, 6400.0000])

In [61]:
sqrt_discriminant = torch.sqrt(discriminant)
sqrt_discriminant

tensor([ 0.0000, 52.9150, 52.9150, 52.9150, 74.9400, 69.2820, 71.7995, 52.9150,
        52.9150, 52.9150, 52.9150, 80.0000])

In [62]:
t1 = (-b - sqrt_discriminant) / (2 * a)
t2 = (-b + sqrt_discriminant) / (2 * a)
t1, t2 = -t1, -t2
t1, t2

(tensor([50.0000, 66.4575, 74.4575, 26.4575, 85.4700, 74.6410, 86.0375, -1.5425,
         72.4575, 71.4575, 51.4575, 79.0000]),
 tensor([ 50.0000,  13.5425,  21.5425, -26.4575,  10.5300,   5.3590,  14.2380,
         -54.4575,  19.5425,  18.5425,  -1.4575,  -1.0000]))

In [63]:
t_min = torch.minimum(t1, t2)
t_max = torch.maximum(t1, t2)
t_min, t_max

(tensor([ 50.0000,  13.5425,  21.5425, -26.4575,  10.5300,   5.3590,  14.2380,
         -54.4575,  19.5425,  18.5425,  -1.4575,  -1.0000]),
 tensor([50.0000, 66.4575, 74.4575, 26.4575, 85.4700, 74.6410, 86.0375, -1.5425,
         72.4575, 71.4575, 51.4575, 79.0000]))

In [64]:
t_min = torch.where(start_in_inner, t_max, t_min)
t_max = torch.where(end_in_inner, t_min, t_max)
t_min, t_max

(tensor([ 50.0000,  13.5425,  21.5425,  26.4575,  10.5300,   5.3590,  14.2380,
         -54.4575,  19.5425,  18.5425,  -1.4575,  -1.0000]),
 tensor([50.0000, 66.4575, 74.4575, 26.4575, 85.4700, 74.6410, 14.2380, -1.5425,
         72.4575, 71.4575, 51.4575, 79.0000]))

In [65]:
closest_out_inner = closest_distance >= inner_radius
closest_out_inner

tensor([ True, False,  True, False, False, False, False,  True,  True,  True,
        False, False])

In [66]:
t_min = torch.where(closest_out_inner & (t_min < 0), t_max, t_min)
t_max = torch.where(closest_out_inner & (t_max > lines[F.length]), t_min, t_max)
t_min, t_max

(tensor([50.0000, 13.5425, 21.5425, 26.4575, 10.5300,  5.3590, 14.2380, -1.5425,
         19.5425, 18.5425, -1.4575, -1.0000]),
 tensor([50.0000, 66.4575, 21.5425, 26.4575, 85.4700, 74.6410, 14.2380, -1.5425,
         19.5425, 18.5425, 51.4575, 79.0000]))

In [ ]:
intersection_min = torch.clamp(t_min / lines[F.length], min=0, max=1)
intersection_max = torch.clamp(t_max / lines[F.length], min=0, max=1)
intersection_min, intersection_max

(tensor([1.0000, 0.1505, 1.0000, 0.6614, 0.1053, 0.0595, 0.2644, 0.0000, 0.9771,
         0.9271, 0.0000, 0.0000]),
 tensor([1.0000, 0.7384, 1.0000, 0.6614, 0.8547, 0.8293, 0.2644, 0.0000, 0.9771,
         0.9271, 0.7917, 1.0000]))

In [ ]:
# For the arcs
ix = lines[F.start_x] + t_min * lines[F.u_x]
iy = lines[F.start_y] + t_min * lines[F.u_y]
jx = lines[F.start_x] + t_max * lines[F.u_x]
jy = lines[F.start_y] + t_max * lines[F.u_y]

In [ ]:
angle1 = torch.atan2(iy - arcs[F.center_y], ix - arcs[F.center_x]) % (2 * torch.pi)
angle2 = torch.atan2(jy - arcs[F.center_y], jx - arcs[F.center_x]) % (2 * torch.pi)
angle1, angle2

(tensor([1.5708, 0.8481, 2.2935, 0.8481, 3.7113, 3.6652, 3.9788, 0.8481, 3.9897,
         0.8481, 2.2935, 4.7124]),
 tensor([1.5708, 2.2935, 2.2935, 0.8481, 1.2849, 5.7596, 3.9788, 0.8481, 3.9897,
         0.8481, 0.8481, 1.5708]))

In [74]:
angle_min = (torch.minimum(angle1, angle2) / torch.pi) -1
angle_max = (torch.maximum(angle1, angle2) / torch.pi) -1
angle_min, angle_max

(tensor([-0.5000, -0.7301, -0.2699, -0.7301, -0.5910,  0.1667,  0.2665, -0.7301,
          0.2699, -0.7301, -0.7301, -0.5000]),
 tensor([-0.5000, -0.2699, -0.2699, -0.7301,  0.1813,  0.8333,  0.2665, -0.7301,
          0.2699, -0.7301, -0.2699,  0.5000]))